
insert into aplicacao.usuario(id, nome, sobrenome, senha, email, data_nascimento, administrador) values(-1, 'Administrador', 'do Sistema', '123', 'admin', '1995-01-01', true);

insert into aplicacao.genero(id, nome) values(1,'Policial');
insert into aplicacao.genero(id, nome) values(2,'Drama');
insert into aplicacao.genero(id, nome) values(3,'Suspense');
insert into aplicacao.genero(id, nome) values(4,'Erótico');
insert into aplicacao.genero(id, nome) values(5,'Ação');
insert into aplicacao.genero(id, nome) values(6,'Guerra');
insert into aplicacao.genero(id, nome) values(7,'Crime');
insert into aplicacao.genero(id, nome) values(8,'Aventura');
insert into aplicacao.genero(id, nome) values(9,'Comédia');
insert into aplicacao.genero(id, nome) values(10,'Fantasia');
insert into aplicacao.genero(id, nome) values(11,'Ficção Científica');
insert into aplicacao.genero(id, nome) values(12,'Espionagem');

insert into aplicacao.video (id,titulo, sinopse, classificacao_etaria, ano, nome_diretor, nome_ator_principal, imagem_path) values(-1,'Pulp Fiction','Vincent Vega (John Travolta) e Jules Winnfield (Samuel L. Jackson) são dois assassinos profissionais trabalham fazendo cobranças para Marsellus Wallace (Ving Rhames), um poderosos gângster. Vega é forçado a sair com a garota do chefe, temendo passar dos limites; enquanto isso, o pugilista Butch Coolidge (Bruce Willis) se mete em apuros por ganhar luta que deveria perder.',18,1995,'Quentin Tarantino','John Travolta','/resources/layout/imagens/folder/pulfiction.jpg');
insert into aplicacao.video (id,titulo, sinopse, classificacao_etaria, ano, nome_diretor, nome_ator_principal, imagem_path) values(-2,'NINFOMANÍACA - VOLUME 1','Bastante machucada e largada em um beco, Joe (Charlotte Gainsbourg) é encontrada por um homem mais velho, Seligman (Stellan Skarsgard), que lhe oferece ajuda. Ele a leva para sua casa, onde possa descansar e se recuperar. Ao despertar, Joe começa a contar detalhes de sua vida para Seligman. Assumindo ser uma ninfomaníaca e que não é, de forma alguma, uma pessoa boa, ela narra algumas das aventuras sexuais que vivenciou para justificar o porquê de sua auto avaliação.',18,2014,'Lars von Trier','Charlotte Gainsbourg','/resources/layout/imagens/folder/ninfomaniaca.jpg');
insert into aplicacao.video (id,titulo, sinopse, classificacao_etaria, ano, nome_diretor, nome_ator_principal, imagem_path) values(-3,'Tudo sobre minha mãe','No dia de seu aniversário, Esteban (Eloy Azorín) ganha de presente da mãe, Manuela (Cecilia Roth), um ingresso para a nova montagem da peça "Um bonde chamado desejo", estrelada por Huma Rojo (Marisa Paredes). Após o espetáculo, ao tentar pegar um autógrafo de Huma, Esteban é atropelado e morre. Manuela resolve então ir até o pai do menino, que vive em Barcelona, para dar a notícia. No caminho, ela encontra o travesti Agrado (Antonia San Juan), a freira Rosa (Penélope Cruz) e a própria Huma Rojo.',18,1999,'Pedro Almodóvar','Cecilia Roth','/resources/layout/imagens/folder/tudosobreminhamae.jpg');
insert into aplicacao.video (id,titulo, sinopse, classificacao_etaria, ano, nome_diretor, nome_ator_principal, imagem_path) values(-4,'Sicario - Terra de Ninguém','A CIA está preparando uma audaciosa operação para deter o grande líder de um cartel de drogas mexicano. Kate Macy (Emily Blunt), policial do FBI, decide participar da ação, mas logo descobre que terá de testar todos os seus limites morais e éticos nesta missão.',16,2015,'Denis Villeneuve','Emily Blunt','/resources/layout/imagens/folder/sicario.jpg');
insert into aplicacao.video (id,titulo, sinopse, classificacao_etaria, ano, nome_diretor, nome_ator_principal, imagem_path) values(-5,'Tropa de Elite','O dia-a-dia do grupo de policiais e de um capitão do BOPE (Wagner Moura), que quer deixar a corporação e tenta encontrar um substituto para seu posto. Paralelamente dois amigos de infância se tornam policiais e se destacam pela honestidade e honra ao realizar suas funções, se indignando com a corrupção existente no batalhão em que atuam.',16,2007,'José Padilha','Wagner Moura','/resources/layout/imagens/folder/tropadeelite.jpg');
insert into aplicacao.video (id,titulo, sinopse, classificacao_etaria, ano, nome_diretor, nome_ator_principal, imagem_path) values(-6,'Um ato de liberdade','Tuvia (Daniel Craig), Zus (Liev Schreiber) e Asael (Jamie Bell) são irmãos que, ao fugir da perseguição nazista aos judeus, se escondem em uma floresta que conhecem desde a infância. De início eles apenas pensam em sobreviver, mas à medida que seus atos de bravura se espalham diversas pessoas passam a procurá-los, em busca de liberdade. Tuvia assume a posição de líder mas é contestado por Zus, que teme que suas decisões os levem à morte.',16,2008,'Edward Zwick','Daniel Craig','/resources/layout/imagens/folder/umatodeliberdade.jpg');
insert into aplicacao.video (id,titulo, sinopse, classificacao_etaria, ano, nome_diretor, nome_ator_principal, imagem_path) values(-7,'Operações especiais','Formada em turismo e trabalhando como atendente em um hotel, Francis (Cléo Pires) se anima com a possibilidade de entrar para a polícia civil. Ela presta o concurso e, após ser aprovada, passa a frequentar o curso de habilitação para policial. Trata-se do mesmo período em que ocorreu a invasão no Complexo do Alemão, com traficantes de vários morros cariocas fugindo para cidades periféricas. É o que acontece em São Judas do Livramento, cidade no interior do estado do Rio de Janeiro, que passa a lidar com uma onda de crimes sem precedentes. Para combatê-los é enviada a unidade liderada pelo incorruptível delegado Paulo Froes (Marcos Caruso), que conta com a presença da ainda iniciante Francis. No batalhão ela precisa lidar com a desconfiança dos demais policiais, especialmente Roni (Thiago Martins), e também com as dificuldades da profissão, dos perigos inerentes ao ofício até a corrupção existente ao seu redor.',14,2014,'Tomás Portella','Cleo Pires','/resources/layout/imagens/folder/operacoesespeciais.jpg');
insert into aplicacao.video (id,titulo, sinopse, classificacao_etaria, ano, nome_diretor, nome_ator_principal, imagem_path) values(-8,'13º Distrito','Brick Mansions é uma área da cidade de Detroit onde a violência tem índices altíssimos, o que fez com que a prefeitura local praticamente abandonasse o local à própria sorte. Com isso, traficantes como Tremaine Alexander (RZA) ganharam status e poder, por mais que sejam combatidos por Lino (David Belle), um especialista em le parkour que tenta erradicar as drogas do local. Entretanto, Lino tem problemas com a polícia, corrompida pelo crime organizado, o que faz com que seja preso. Um dos poucos que tentam realmente seguir as leis é Damien Collier (Paul Walker), um detetive que recebe como missão entrar em Brick Mansions para resgatar uma bomba que pode matar milhões. Para tanto, ele precisa contar com a ajuda de Lino, que deseja retornar ao local para resgatar Lola (Catalina Denis), sua namorada, que foi raptada pelos capangas de Tremaine.',14,2013,'Camille Delamarre','Paul Walker','/resources/layout/imagens/folder/13distrito.jpg');
insert into aplicacao.video (id,titulo, sinopse, classificacao_etaria, ano, nome_diretor, nome_ator_principal, imagem_path) values(-9,'Que horas ela volta?','Val (Regina Casé), uma mulher que deixou a filha no interior de Pernambuco e foi ser babá em São Paulo, atrás de estabilidade financeira. Treze anos depois, sua filha resolve ir para São Paulo tentar vestibular. Mas a menina não se comporta do jeito que os patrões de Val esperam.',12,2015,'Anna Muylaert','Regina Casé','/resources/layout/imagens/folder/seraqueelavolta.jpg');
insert into aplicacao.video (id,titulo, sinopse, classificacao_etaria, ano, nome_diretor, nome_ator_principal, imagem_path) values(-10,'Into the wild','Christopher McCandless (Emile Hirsch) é um jovem recém-formado, que decide viajar sem rumo pelos Estados Unidos em busca da liberdade. Durante sua jornada pela Dakota do Sul, Arizona e Califórnia ele conhece pessoas que mudam sua vida, assim como sua presença também modifica as delas. Até que, após dois anos na estrada, Christopher decide fazer a maior das viagens e partir rumo ao Alasca.',12,2008,'Sean Penn','Emile Hirsch','/resources/layout/imagens/folder/intothewild.jpg');


insert into aplicacao.filme values(-1,-1);
insert into aplicacao.filme values(-2,-2);
insert into aplicacao.filme values(-3,-3);
insert into aplicacao.filme values(-4,-4);
insert into aplicacao.filme values(-5,-5);
insert into aplicacao.filme values(-6,-6);
insert into aplicacao.filme values(-7,-7);
insert into aplicacao.filme values(-8,-8);
insert into aplicacao.filme values(-9,-9);
insert into aplicacao.filme values(-10,-10);

insert into aplicacao.seriado (id, sinopse, classificacao_etaria, nome_diretor, ano, titulo, desenho, imagem_path) values(-1,'Matthew Michael Murdock (Charlie Cox) é um jovem atleta e excelente aluno. Ainda na adolescência, um acidente envolvendo um caminhão que carregava lixos tóxicos o deixou cego e fez com que ele desenvolvesse vários sentidos. Quando Matt decide vestir o uniforme e adotar o nome Demolidor (Daredevil), leva uma vida dupla: é advogado durante o dia, e, à noite, protege as ruas de Hells Kitchen, seu bairro em Nova York.',18,'Phil Abraham',2015,'Demolidor',false,'/resources/layout/imagens/folder/demolidor.jpg');
insert into aplicacao.seriado (id, sinopse, classificacao_etaria, nome_diretor, ano, titulo, desenho, imagem_path) values(-2,'Há muito tempo, em um tempo esquecido, uma força destruiu o equilíbrio das estações. Em uma terra onde os verões podem durar vários anos e o inverno toda uma vida, as reivindicações e as forças sobrenaturais correm as portas do Reino dos Sete Reinos. A irmandade da Patrulha da Noite busca proteger o reino de cada criatura que pode vir de lá da Muralha, mas já não tem os recursos necessários para garantir a segurança de todos. Depois de um verão de dez anos, um inverno rigoroso promete chegar com um futuro mais sombrio. Enquanto isso, conspirações e rivalidades correm no jogo político pela disputa do Trono de Ferro, o símbolo do poder absoluto.',18,'Tim Van Patten',2011,'Game of Trhones',false,'/resources/layout/imagens/folder/got.jpg');
insert into aplicacao.seriado (id, sinopse, classificacao_etaria, nome_diretor, ano, titulo, desenho, imagem_path) values(-3,'Spartacus: Blood and Sand, conta a história de Spartacus (Andy Whitfield), o escravo de guerra romano que se tornou um gladiador e liderou a mais famosa revolução da Roma Antiga. Quando é separado de sua esposa e os dois são colocados a venda, Spartacus é jogado em uma Arena para a diversão da plebe, mas surpreende a todos quando vence as quatro batalhas. E ele não irá parar enquanto não reencontrar sua esposa.',18,'Sam Raimi',2010,'Spartacus',false,'/resources/layout/imagens/folder/spartacus.jpg');
insert into aplicacao.seriado (id, sinopse, classificacao_etaria, nome_diretor, ano, titulo, desenho, imagem_path) values(-4,'Depois de presenciar o suicídio de uma mulher (que é exatamente como ela) em uma estação de trem, Sarah Manning (Tatiana Maslany) faz o que qualquer um faria: assume a identidade da suicida para tentar resolver os próprios problemas financeiros. Mas logo ela descobre que está no centro de um mistério que vai mudar sua vida, quando se vê cara a cara com mais três mulheres idênticas a ela. Todas são clones, e precisam salvar as próprias peles enquanto tentam descobrir quem são os responsáveis pelos experimentos genéticos.',16,'John Fawcett',2013,'Orphan Black',false,'/resources/layout/imagens/folder/orphanblack.jpg');
insert into aplicacao.seriado (id, sinopse, classificacao_etaria, nome_diretor, ano, titulo, desenho, imagem_path) values(-5,'Grupos de pessoas ao redor do mundo que estão ligadas mentalmente, e precisam achar uma maneira de sobreviver sendo caçados por aqueles que os veem como uma ameaça para a ordem mundial.',16,'Joseph Mawle',2015,'Sense8',false,'/resources/layout/imagens/folder/sense8.png');
insert into aplicacao.seriado (id, sinopse, classificacao_etaria, nome_diretor, ano, titulo, desenho, imagem_path) values(-6,'Após a prisão de Lincoln Burrows (Dominic Purcell), condenado por um crime que não cometeu, o engenheiro Michael Scofield (Wentworth Miller) bola um plano para tirar o irmão da cadeia. Enviado para Fox River ao lado de Lincoln, Michael começa a executar a sua estratégia, mas logo percebe que está no meio de uma perigosa conspiração. Para garantir a liberdade da sua família, ele precisará enganar a Dra. Sara Tancredi (Sarah Wayne Callies) e se associar a criminosos condenados, como Fernando Sucre (Amaury Nolasco), Theodore (T-Bag) Bagwell (Robert Knepper) e John Abruzzi (Peter Stormare).',16,'Brett Ratner',2005,'Prison Break',false,'/resources/layout/imagens/folder/prisonbreak.jpg');
insert into aplicacao.seriado (id, sinopse, classificacao_etaria, nome_diretor, ano, titulo, desenho, imagem_path) values(-7,'Um grupo diverso de brilhantes e controlados recrutas chega à base do FBI em Quantico para o treinamento. Eles são considerados alguns dos melhores agentes, mas, paradoxalmente, um deles se torna suspeito de planejar o maior ataque em Nova York desde o dia 11 de setembro.',14,'Patrick R. Norris',2015,'Quantico',false,'/resources/layout/imagens/folder/quantico.jpg');
insert into aplicacao.seriado (id, sinopse, classificacao_etaria, nome_diretor, ano, titulo, desenho, imagem_path) values(-8,'Michaela, Wes, Laurel e Patrick são ambiciosos calouros de Direito da prestigiada academia East Coast Law School, onde apenas os melhores alunos podem participar de casos reais. Eles competem entre si para conseguir a atenção da carismática e sedutora Professora Annalise DeWitt (Viola Davis), na aula de Direito Criminal 1, também conhecida como Como Se Livrar de Um Assassinato',14,'Bill DElia',2014,'How to Get Away With Murder',false,'/resources/layout/imagens/folder/howtogetawaywithmurder.jpg');
insert into aplicacao.seriado (id, sinopse, classificacao_etaria, nome_diretor, ano, titulo, desenho, imagem_path) values(-9,'Na cidade fictícia de Storybrooke, no Maine, Regina (Lana Parrilla) é uma rainha má que rouba memórias graças à maldição obtida por meio de Rumplestiltskin (Robert Carlyle). Suas vítimas viveram, portanto, uma realidade imutável durante 28 anos, sem ter qualquer noção de sua idade. Todas as esperanças estão depositadas em Emma Swan (Jennifer Morrison), filha da Branca de Neve (Ginnifer Goddwin) e do Príncipe Encantado (Josh Dallas). Ela é a única pessoa com a capacidade de quebrar a maldição e recuperar as lembranças perdidas, pois foi transportada do mundo de conto de fadas antes de ser atingida pelo feitiço.',12,'Mark Mylod',2011,'Once Upon a Time',false,'/resources/layout/imagens/folder/onceuponatime.jpg');
insert into aplicacao.seriado (id, sinopse, classificacao_etaria, nome_diretor, ano, titulo, desenho, imagem_path) values(-10,'Seis jovens são unidos por laços familiares, românticos e, principalmente, de amizade, enquanto tentam vingar em Nova York. Rachel é a garota mimada que deixa o noivo no altar para viver com a amiga dos tempos de escola Monica, sistemática e apaixonada pela culinária. Monica é irmã de Ross, um paleontólogo que é abandonado pela esposa, que descobriu ser lésbica. Do outro lado do corredor do apartamento de Monica e Rachel, moram Joey, um ator frustrado, e Chandler, de profissão misteriosa. A turma é completa pela exótica Phoebe.',12,'James Burrows',1994,'Friends',false,'/resources/layout/imagens/folder/friends.jpg');
