insert into aplicacao.usuario(id, nome, sobrenome, senha, email, data_nascimento, administrador) values(-1, 'Administrador', 'do Sistema', '123', 'admin', '1995-01-01', true);

insert into aplicacao.genero(id, nome) values(1,'Policial');
insert into aplicacao.genero(id, nome) values(2,'Drama');
insert into aplicacao.genero(id, nome) values(3,'Suspense');
insert into aplicacao.genero(id, nome) values(4,'Erótico');
insert into aplicacao.genero(id, nome) values(5,'Ação');
insert into aplicacao.genero(id, nome) values(6,'Guerra');
insert into aplicacao.genero(id, nome) values(7,'Crime');
insert into aplicacao.genero(id, nome) values(8,'Aventura');
insert into aplicacao.genero(id, nome) values(9,'Comédia');
insert into aplicacao.genero(id, nome) values(10,'Fantasia');
insert into aplicacao.genero(id, nome) values(11,'Ficção Científica');
insert into aplicacao.genero(id, nome) values(12,'Espionagem');

insert into aplicacao.video (id,titulo, sinopse, classificacao_etaria, ano, nome_diretor, nome_ator_principal, imagem_path) values(1,'Pulp Fiction','Vincent Vega (John Travolta) e Jules Winnfield (Samuel L. Jackson) são dois assassinos profissionais trabalham fazendo cobranças para Marsellus Wallace (Ving Rhames), um poderosos gângster. Vega é forçado a sair com a garota do chefe, temendo passar dos limites; enquanto isso, o pugilista Butch Coolidge (Bruce Willis) se mete em apuros por ganhar luta que deveria perder.',18,1995,'Quentin Tarantino','John Travolta','//resources//layout//imagens//folder//pulfiction.jpg');
insert into aplicacao.video (id,titulo, sinopse, classificacao_etaria, ano, nome_diretor, nome_ator_principal, imagem_path) values(2,'NINFOMANÍACA - VOLUME 1','Bastante machucada e largada em um beco, Joe (Charlotte Gainsbourg) é encontrada por um homem mais velho, Seligman (Stellan Skarsgard), que lhe oferece ajuda. Ele a leva para sua casa, onde possa descansar e se recuperar. Ao despertar, Joe começa a contar detalhes de sua vida para Seligman. Assumindo ser uma ninfomaníaca e que não é, de forma alguma, uma pessoa boa, ela narra algumas das aventuras sexuais que vivenciou para justificar o porquê de sua auto avaliação.',18,2014,'Lars von Trier','Charlotte Gainsbourg','//resources//layout//imagens//folder//ninfomaniaca.jpg');
insert into aplicacao.video (id,titulo, sinopse, classificacao_etaria, ano, nome_diretor, nome_ator_principal, imagem_path) values(3,'Tudo sobre minha mãe','No dia de seu aniversário, Esteban (Eloy Azorín) ganha de presente da mãe, Manuela (Cecilia Roth), um ingresso para a nova montagem da peça "Um bonde chamado desejo", estrelada por Huma Rojo (Marisa Paredes). Após o espetáculo, ao tentar pegar um autógrafo de Huma, Esteban é atropelado e morre. Manuela resolve então ir até o pai do menino, que vive em Barcelona, para dar a notícia. No caminho, ela encontra o travesti Agrado (Antonia San Juan), a freira Rosa (Penélope Cruz) e a própria Huma Rojo.',18,1999,'Pedro Almodóvar','Cecilia Roth','//resources//layout//imagens//folder//tudosobreminhamae.jpg');
insert into aplicacao.video (id,titulo, sinopse, classificacao_etaria, ano, nome_diretor, nome_ator_principal, imagem_path) values(4,'Sicario - Terra de Ninguém','A CIA está preparando uma audaciosa operação para deter o grande líder de um cartel de drogas mexicano. Kate Macy (Emily Blunt), policial do FBI, decide participar da ação, mas logo descobre que terá de testar todos os seus limites morais e éticos nesta missão.',16,2015,'Denis Villeneuve','Emily Blunt','//resources//layout//imagens//folder//sicario.jpg');
insert into aplicacao.video (id,titulo, sinopse, classificacao_etaria, ano, nome_diretor, nome_ator_principal, imagem_path) values(5,'Tropa de Elite','O dia-a-dia do grupo de policiais e de um capitão do BOPE (Wagner Moura), que quer deixar a corporação e tenta encontrar um substituto para seu posto. Paralelamente dois amigos de infância se tornam policiais e se destacam pela honestidade e honra ao realizar suas funções, se indignando com a corrupção existente no batalhão em que atuam.',16,2007,'José Padilha','Wagner Moura','//resources//layout//imagens//folder//tropadeelite.jpg');
insert into aplicacao.video (id,titulo, sinopse, classificacao_etaria, ano, nome_diretor, nome_ator_principal, imagem_path) values(6,'Um ato de liberdade','Tuvia (Daniel Craig), Zus (Liev Schreiber) e Asael (Jamie Bell) são irmãos que, ao fugir da perseguição nazista aos judeus, se escondem em uma floresta que conhecem desde a infância. De início eles apenas pensam em sobreviver, mas à medida que seus atos de bravura se espalham diversas pessoas passam a procurá-los, em busca de liberdade. Tuvia assume a posição de líder mas é contestado por Zus, que teme que suas decisões os levem à morte.',16,2008,'Edward Zwick','Daniel Craig','//resources//layout//imagens//folder//umatodeliberdade.jpg');
insert into aplicacao.video (id,titulo, sinopse, classificacao_etaria, ano, nome_diretor, nome_ator_principal, imagem_path) values(7,'Operações especiais','Formada em turismo e trabalhando como atendente em um hotel, Francis (Cléo Pires) se anima com a possibilidade de entrar para a polícia civil. Ela presta o concurso e, após ser aprovada, passa a frequentar o curso de habilitação para policial. Trata-se do mesmo período em que ocorreu a invasão no Complexo do Alemão, com traficantes de vários morros cariocas fugindo para cidades periféricas. É o que acontece em São Judas do Livramento, cidade no interior do estado do Rio de Janeiro, que passa a lidar com uma onda de crimes sem precedentes. Para combatê-los é enviada a unidade liderada pelo incorruptível delegado Paulo Froes (Marcos Caruso), que conta com a presença da ainda iniciante Francis. No batalhão ela precisa lidar com a desconfiança dos demais policiais, especialmente Roni (Thiago Martins), e também com as dificuldades da profissão, dos perigos inerentes ao ofício até a corrupção existente ao seu redor.',14,2014,'Tomás Portella','Cleo Pires','//resources//layout//imagens//folder//operacoesespeciais.jpg');
insert into aplicacao.video (id,titulo, sinopse, classificacao_etaria, ano, nome_diretor, nome_ator_principal, imagem_path) values(8,'13º Distrito','Brick Mansions é uma área da cidade de Detroit onde a violência tem índices altíssimos, o que fez com que a prefeitura local praticamente abandonasse o local à própria sorte. Com isso, traficantes como Tremaine Alexander (RZA) ganharam status e poder, por mais que sejam combatidos por Lino (David Belle), um especialista em le parkour que tenta erradicar as drogas do local. Entretanto, Lino tem problemas com a polícia, corrompida pelo crime organizado, o que faz com que seja preso. Um dos poucos que tentam realmente seguir as leis é Damien Collier (Paul Walker), um detetive que recebe como missão entrar em Brick Mansions para resgatar uma bomba que pode matar milhões. Para tanto, ele precisa contar com a ajuda de Lino, que deseja retornar ao local para resgatar Lola (Catalina Denis), sua namorada, que foi raptada pelos capangas de Tremaine.',14,2013,'Camille Delamarre','Paul Walker','//resources//layout//imagens//folder//13distrito.jpg');
insert into aplicacao.video (id,titulo, sinopse, classificacao_etaria, ano, nome_diretor, nome_ator_principal, imagem_path) values(9,'Que horas ela volta?','Val (Regina Casé), uma mulher que deixou a filha no interior de Pernambuco e foi ser babá em São Paulo, atrás de estabilidade financeira. Treze anos depois, sua filha resolve ir para São Paulo tentar vestibular. Mas a menina não se comporta do jeito que os patrões de Val esperam.',12,2015,'Anna Muylaert','Regina Casé','//resources//layout//imagens//folder//seraqueelavolta.jpg');
insert into aplicacao.video (id,titulo, sinopse, classificacao_etaria, ano, nome_diretor, nome_ator_principal, imagem_path) values(10,'Into the wild','Christopher McCandless (Emile Hirsch) é um jovem recém-formado, que decide viajar sem rumo pelos Estados Unidos em busca da liberdade. Durante sua jornada pela Dakota do Sul, Arizona e Califórnia ele conhece pessoas que mudam sua vida, assim como sua presença também modifica as delas. Até que, após dois anos na estrada, Christopher decide fazer a maior das viagens e partir rumo ao Alasca.',12,2008,'Sean Penn','Emile Hirsch','//resources//layout//imagens//folder//intothewild.jpg');


insert into aplicacao.filme values(1,1);
insert into aplicacao.filme values(2,2);
insert into aplicacao.filme values(3,3);
insert into aplicacao.filme values(4,4);
insert into aplicacao.filme values(5,5);
insert into aplicacao.filme values(6,6);
insert into aplicacao.filme values(7,7);
insert into aplicacao.filme values(8,8);
insert into aplicacao.filme values(9,9);
insert into aplicacao.filme values(10,10);